apiVersion: v1
kind: Service
metadata:
  name: wil-app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wil-app
  ports:
    - protocol: TCP
      port: 80          # Port inside the cluster
      targetPort: 80    # Port on the pod
      nodePort: 30080   # This matches your k3d mapping